### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by SVronskiy** [alcounit/selenosis#12]
Hello,  @alcounit !

Thank you for the Selenosis!

I'm not able to start video in Selenosis. When I open session in selenoid-ui, I have only logs, but not video.
Is vnc/video supported in Selenosis?

My browsers.yaml:
```
chrome:
  defaultVersion: "88.0"
  path: "/"
  spec:
    env:
    - name: TZ
      value: Europe/Kiev
    - name: SCREEN_RESOLUTION
      value: "1920x1080x24"
    - name: ENABLE_VNC
      value: "true"
  versions:
    '85.0':
      image: selenoid/vnc:chrome_85.0
    '86.0':
      image: selenoid/vnc:chrome_86.0
    '87.0':
      image: selenoid/vnc:chrome_87.0
    '88.0':
      image: registry.mydns.com/sc88

```
