### ISSUE TITLE
Android native (not web) application UI test

### ISSUE THREAD

**Issue by SVronskiy** [alcounit/selenosis#14]
Hello, @alcounit !

I'm trying to run android native (not web) application UI test, following guid: [Execute Android Appium Tests in Docker Containers Using Selenoid](https://www.automatetheplanet.com/execute-android-appium-tests-docker-selenoid/).

I have enabled nested virtualization on k8s nodes via  [How To Enable Nested Virtualization In KVM In Linux](https://ostechnix.com/how-to-enable-nested-virtualization-in-kvm-in-linux/#:~:text=Open%20Virt-manager%20GUI%20application,configuration%20window%20and%20click%20Apply), but still getting exception:

```
emulator: ERROR: x86 emulation currently requires hardware acceleration!
CPU acceleration status: /dev/kvm is not found: VT disabled in BIOS or KVM kernel module not loaded
More info on configuring VM acceleration on Linux:
https://developer.android.com/studio/run/emulator-acceleration#vm-linux
General information on acceleration: https://developer.android.com/studio/run/emulator-acceleration.
```

Please help me to solve the problem!

My browsers.yaml:
```
android:
  defaultVersion: "8.0"
  path: "/"
  versions:
    '10.0':
      image: selenoid/android:10.0
    '9.0':
      image: selenoid/android:9.0
    '8.0':
      image: selenoid/android:8.0

```

My android.cs:
```
using System;
using System.Text;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using OpenQA.Selenium;
using OpenQA.Selenium.Appium;
using OpenQA.Selenium.Appium.Android;

namespace Selenium
{
    [TestClass]
    public class AndroidTests
    {
        //private Appium.A
        private static AndroidDriver <AndroidElement> _driver;

        [TestMethod]
        public void PerformActionsButtons()
        {
            
            By byScrollLocator = new ByAndroidUIAutomator("new UiSelector().text(\"Views\");");
            var viewsButton = _driver.FindElement(byScrollLocator);
            viewsButton.Click();
            var controlsViewButton = _driver.FindElementByXPath("//*[@text='Controls']");
            controlsViewButton.Click();
            var lightThemeButton = _driver.FindElementByXPath("//*[@text='1. Light Theme']");
            lightThemeButton.Click();
            var saveButton = _driver.FindElementByXPath("//*[@text='Save']");
            Assert.IsTrue(saveButton.Enabled);
        }

        [ClassInitialize]
        public static void ClassInitialize(TestContext context)
        {
            var appiumOptions = new AppiumOptions();
            appiumOptions.AddAdditionalCapability("deviceName", "android");
            appiumOptions.AddAdditionalCapability("appPackage", "io.appium.android.apis");
            appiumOptions.AddAdditionalCapability("version", "8.0");
            appiumOptions.AddAdditionalCapability("appActivity", ".ApiDemos");
            appiumOptions.AddAdditionalCapability("app", "https://github.com/appium/appium/raw/master/sample-code/apps/ApiDemos-debug.apk"); // upload ApiDemos-debug.apk from Resources folder to public file share.
            appiumOptions.AddAdditionalCapability("enableVNC", true);
            appiumOptions.AddAdditionalCapability("enableVideo", true);
            var timeout = TimeSpan.FromSeconds(120);
            // Change with your Selenoid hub instance URL.
            _driver = new AndroidDriver<AndroidElement>(new Uri("http://selenosis.local:31000/wd/hub"), appiumOptions, timeout);
            _driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(120);
            _driver.Manage().Timeouts().AsynchronousJavaScript = TimeSpan.FromSeconds(120);
        }
        [TestCleanup]
        public void TestCleanup()
        {
            _driver?.CloseApp();
            _driver?.Quit();
            _driver?.Dispose();
        }
    }
}
```

**Comment by alcounit** [comment]
Hi @SVronskiy.
Please more info about your environment.
At first look, host system that runs k8 nodes VM's doesn't support virtualization or it is not enabled. Can you confirm it?
Share output from host system:
# egrep "(svm|vmx)" /proc/cpuinfo

**Comment by SVronskiy** [comment]
In test env I'm using ubuntu KVM on host, 4 ubuntu VM with k8s nodes, virtualization and nested virtualization are enabled.

egrep "(svm|vmx)" /proc/cpuinfo on host machine returns 8 strings:

flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni dtes64 monitor ds_cpl **vmx** est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 popcnt lahf_lm pti tpr_shadow vnmi flexpriority ept vpid dtherm ida

egrep "(svm|vmx)" /proc/cpuinfo on virtual machines (k8s nodes) returns 4 strings:

root@kuber2:~# egrep "(svm|vmx)" /proc/cpuinfo
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni **vmx** ssse3 cx16 sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer hypervisor lahf_lm cpuid_fault pti tpr_shadow vnmi flexpriority ept vpid tsc_adjust arat umip arch_capabilities

**Comment by alcounit** [comment]
Looks like I figured out where is the problem, but unfortunately, I can't verify it. Hope you can help me with verification. 
Please update your deployment manifect (03-selenosis.yaml) and change the image to **alcounit/selenosis:develop**
Also, update your browsers config to the following:
```yaml
android:
  defaultVersion: "8.0"
  path: "/"
  versions:
    '10.0':
      image: selenoid/android:10.0
      privileged: true
    '9.0':
      image: selenoid/android:9.0
      privileged: true
    '8.0':
      image: selenoid/android:8.0
      privileged: true
```

**Comment by SVronskiy** [comment]
I've updated container image and configmap as you mentioned above. 
Previous error ("/dev/kvm is not found") gone, but now pod terminates with another error and I have the following pod logs:
```
Waiting X server...
Logging to: /tmp/fluxbox.log
Waiting X server...
Waiting X server...
Waiting X server...
Waiting X server...
Waiting X server...
 --- x11vnc loop: 1 ---
* daemon not running; starting now at tcp:5037
 --- x11vnc loop: waiting for: 93
PORT=5900
* daemon started successfully
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: device offline
WARNING. Using fallback path for the emulator registration directory.
```

I get the same error in pod logs if using the following Test code:
```

        [TestInitialize()]
        public void SetupTest()
        {
            DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.SetCapability("browserName", "android");
            capabilities.SetCapability("browserVersion", "8.0");
            capabilities.SetCapability("appActivity", ".ApiDemos");
            capabilities.SetCapability("app", "https://github.com/appium/appium/raw/master/sample-code/apps/ApiDemos-debug.apk");
            capabilities.SetCapability("appPackage", "io.appium.android.apis");
            capabilities.SetCapability("enableVNC", true);
            capabilities.SetCapability("screenResolution", "1920x1080x24");
            capabilities.SetCapability("skin", "WSVGA");
            driver = new RemoteWebDriver(new Uri("http://selenosis.local:31000/wd/hub"), capabilities);


            driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(120);

        }

```

**Comment by alcounit** [comment]
Looks like path should be "/wd/hub"

**Comment by SVronskiy** [comment]
I have aplied change to configmap and restarted selenosis pods, but nothing changed in logs. For a moment I've testes android 7.0, 8.0, 8,1, pod logs are completed after "adb: device offline" or "adb: no devices/emulators found".

**Comment by alcounit** [comment]
Can you please share logs from selenosis?

**Comment by SVronskiy** [comment]
Scaled selenosis to one, here logs:
```
time="2021-02-17T18:32:37Z" level=info msg="starting selenosis v0.0.6.7-develop"
time="2021-02-17T18:32:37Z" level=info msg="browsers config file loaded"
time="2021-02-17T18:32:37Z" level=info msg="config watcher started"
time="2021-02-17T18:32:37Z" level=info msg="kubernetes client created"
time="2021-02-17T18:33:00Z" level=info msg=session request="POST /wd/hub/session" request_id=32a9abe2-2dfd-4875-ba45-284b0e9686dc time_elapsed=0.00s
time="2021-02-17T18:33:00Z" level=info msg="starting browser from image: selenoid/android:8.0" request="POST /wd/hub/session" request_id=32a9abe2-2dfd-4875-ba45-284b0e9686dc time_elapsed=0.08s
time="2021-02-17T18:33:51Z" level=error msg="failed to start browser: container service is not ready http://selenoid-android-8-0-cb358296-e357-4a92-bd2c-bbcacd837778.seleniferous:4444" request="POST /wd/hub/session" request_id=32a9abe2-2dfd-4875-ba45-284b0e9686dc time_elapsed=51.78s
```
logs of pod:
```
Waiting X server...
Logging to: /tmp/fluxbox.log
Waiting X server...
Waiting X server...
Waiting X server...
* daemon not running; starting now at tcp:5037
 --- x11vnc loop: 1 ---
* daemon started successfully
adb: no devices/emulators found
 --- x11vnc loop: waiting for: 88
PORT=5900
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
adb: no devices/emulators found
```

**Comment by alcounit** [comment]
@SVronskiy thanks, 
I've pushed a new selenosis image with a small fix + let's increase timeouts browser readiness.
Please use this manifest to update selenosis deployment.
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenosis
  namespace: selenosis
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: selenosis
  template:
    metadata:
      labels:
        app: selenosis
      namespace: selenosis
    spec:
      containers:
      - args: ["/selenosis", "--browsers-config", "./config/browsers.yaml", "--namespace", "selenosis", "--service-name", "seleniferous", "--browser-limit", "40", "--proxy-image", "alcounit/seleniferous:v0.0.2-develop", "--browser-wait-timeout", "3m0s", "--session-wait-timeout", "1m30s", "--session-idle-timeout", "7m0s"]
        image: alcounit/selenosis:develop
        name: selenosis
        ports:
        - containerPort: 4444
          name: selenium
          protocol: TCP
        volumeMounts:
        - mountPath: ./config
          name: browsers-config
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 4444
          periodSeconds: 2
          initialDelaySeconds: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 4444
          periodSeconds: 2
          initialDelaySeconds: 3
      volumes:
      - name: browsers-config
        configMap:
          name: selenosis-config

```
