### ISSUE TITLE
Add pod toleration to config

### ISSUE THREAD

**Issue by alcounit** [alcounit/selenosis#16]
Hello, @alcounit !

I'm currently using selenosis nodeselector, but I need to make baremetal k8s node avaliable only for selenosis ui tests. I need pod toleration similar to https://aerokube.com/moon/latest/#tolerations - is it possible to implement?

_Originally posted by @SVronskiy in https://github.com/alcounit/selenosis/issues/14#issuecomment-783837915_

**Comment by alcounit** [comment]
Hi @SVronskiy
Please check fresh build: alcounit/selenosis:v0.0.8-develop
Update you browser config like:
```yaml
---
    chrome:
        defaultVersion: "68.0"
        path: /
        meta: 
          labels:
          environment: production
          app: projectx
        spec:
          tolerations:
          - key: key1
            operator: Exists
            value: value1
            effect: NoExecute
            tolerationSeconds: 3600
...
```
