### ISSUE TITLE
Long pod name after moving image to ECR

### ISSUE THREAD

**Issue by shlomitsur** [alcounit/selenosis#33]
Hello @alcounit!
To avert the rate-limit I've moved the images (selenosis, seleniferous, chrome) to ecr.
selenosis & seleniferous works well but the chrome pods are failing because the pod name is longer than 63 characters:

`"failed to start browser: failed to create pod Pod \"543052680787-dkr-ecr-us-west-2-amazonaws-com-chrome-89-0-e2f3f465-a0f4-42a1-8e56-b88ca0e35f6d\" is invalid: [metadata.labels: Invalid value: \"543052680787-dkr-ecr-us-west-2-amazonaws-com-chrome-89-0-e2f3f465-a0f4-42a1-8e56-b88ca0e35f6d\": must be no more than 63 characters, spec.hostname: Invalid value: \"543052680787-dkr-ecr-us-west-2-amazonaws-com-chrome-89-0-e2f3f465-a0f4-42a1-8e56-b88ca0e35f6d\": must be no more than 63 characters]" 
`

browser.yaml:
```
chrome:
  defaultVersion: "89.0"
  path: "/"
  kernelCaps:
  - SYS_ADMIN
  versions:
    '89.0':
      image: 543037328387.dkr.ecr.us-west-2.amazonaws.com/chrome:89.0
      spec:
        resources:
          requests:
            memory: 1Gi
            cpu: '1'
          limits:
            memory: 1Gi
            cpu: '1'
```

Thank you
