### ISSUE TITLE
Browser pods still deleted when overriding coredns config in Azure Kubernetes Service

### ISSUE THREAD

**Issue by beerai** [alcounit/selenosis#36]
Since you can't edit the corefile directly, you need to [override the default config](https://docs.microsoft.com/en-us/azure/aks/coredns-custom) using ConfigMaps. Using Kubernetes version 1.18.14 and the following ConfigMap:

```yaml
apiVersion: v1
data:
  selenosis.server: |
    selenosis.svc.cluster.local:53 {
        errors
        kubernetes cluster.local {
          namespaces selenosis
        }
    }
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
```

I can observe a small number of tests executing properly but at some point they all grind to a halt and the logs on selenosis are full of 
![image](https://user-images.githubusercontent.com/2687469/116643322-2a129380-a9b4-11eb-828a-d838604c0154.png)
