### ISSUE TITLE
Session wait timeout seems to be ignored

### ISSUE THREAD

**Issue by beerai** [alcounit/selenosis#40]
Here's my selenosis manifest
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenosis
  namespace: selenosis
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 2
  selector:
    matchLabels:
      app: selenosis
  template:
    metadata:
      labels:
        app: selenosis
        selenosis.app.type: worker
      namespace: selenosis
    spec:
      containers:
      - args: ["/selenosis", "--browsers-config", "./config/browsers.json", "--namespace", "selenosis", "--service-name", "seleniferous", "--browser-limit", "60", "--proxy-image", "alcounit/seleniferous:v1.0.1", "--session-wait-timeout", "120s", "--browser-wait-timeout", "120s"]
        image: alcounit/selenosis:v1.0.4
        name: selenosis
        resources:
          limits:
            cpu: "1"
            memory: "128Mi"
          requests:
            cpu: "0.4"
            memory: "128Mi"
        ports:
        - containerPort: 4444
          name: selenium
          protocol: TCP
        volumeMounts:
        - mountPath: ./config
          name: browsers-config
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /healthz
            port: 4444
          periodSeconds: 2
          initialDelaySeconds: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 4444
          periodSeconds: 2
          initialDelaySeconds: 3
      volumes:
      - name: browsers-config
        configMap:
          name: selenosis-config
```

Note that I've set --session-wait-timeout duration to 120s.
When I look at the logs of one of the selenosis pods, I see a lot of these messages:

```
time="2021-05-11T03:56:06Z" level=info msg="starting browser from image: selenoid/vnc:chrome_90.0" request="POST /wd/hub/session" request_id=0a95994c-c7ba-4f0f-a009-a220f8dc531a time_elapsed=0.00s
time="2021-05-11T03:57:09Z" level=warning msg="Client disconnected" request="POST /wd/hub/session" request_id=06e1388a-336d-46ee-a70a-76505bcd00c2 time_elapsed=126.31s
time="2021-05-11T03:58:16Z" level=warning msg="Client disconnected" request="POST /wd/hub/session" request_id=0a95994c-c7ba-4f0f-a009-a220f8dc531a time_elapsed=129.11s
```

Meanwhile, my tests are failing with this exception:
```
The HTTP request to the remote WebDriver server for URL http://20.40.173.240:4444/wd/hub/session timed out after 60 seconds. ---> System.Net.WebException: The operation has timed out
```

All of my selenium timeouts are greater than 60 seconds, as are the ones I configured in Selenosis' args. Any ideas where the 60 seconds is coming from?

EDIT: I'm not sure if this is relevant but I see a few of these in the logs too:
```
time="2021-05-11T03:54:48Z" level=error msg="failed to start browser: failed to create pod pods \"vnc-chrome-90-0-ccdf79ba-a398-4243-b1d1-9dc08886b68a\" is forbidden: exceeded quota: selenosis-pod-limit, requested: pods=1, used: pods=81, limited: pods=81" request="POST /wd/hub/session" request_id=b69af977-4d72-4d6c-99ba-145bc0b1ab3c time_elapsed=0.01s
```

I've set the browser limit to 60 and have each of my 30 agents running 2 tests, so they're not trying to run > 60 tests. Where does the "selenosis-pod-limit" come from? I see it fluctuates but what determines that limit?

**Comment by alcounit** [comment]
hi @beerai,
```
Note that I've set --session-wait-timeout duration to 120s.
When I look at the logs of one of the selenosis pods, I see a lot of these messages:
```
Can you share your browsers config and full logs(seleniferous + browser) from browser pod that hasn't completed a new session request.
```
All of my selenium timeouts are greater than 60 seconds, as are the ones I configured in Selenosis' args. Any ideas where the 60 seconds is coming from?
```
Do you have any loadbalancer before selenosis? If so, any timeouts there?

```
I've set the browser limit to 60 and have each of my 30 agents running 2 tests, so they're not trying to run > 60 tests. Where does the "selenosis-pod-limit" come from? I see it fluctuates but what determines that limit?
```
How many non browser pods are running in selenosis namespace? please list them all coz deployment that you shared consists of 2 selenosis replicas with browser limit is 60, but log shows resource quota limit 81 :)

**Comment by beerai** [comment]
> Can you share your browsers config and full logs(seleniferous + browser) from browser pod that hasn't completed a new session request.

Sure. Here's the browser config:
```json
{
    "chrome": {
        "defaultVersion": "90.0",
        "path": "/",
        "spec": {
            "resources": {
              "requests": {
                "memory": "1.5Gi",
                "cpu": "1"
              },
              "limits": {
                "memory": "2Gi",
                "cpu": "1.5"
              }
            },
            "tolerations": [
                {
                  "key": "virtual-kubelet.io/provider",
                  "operator": "Exists"
                },
                {
                    "key" : "azure.com/aci",
                    "effect": "NoSchedule"
                }
              ],
            "nodeSelector": {
                "kubernetes.io/role": "agent",
                "beta.kubernetes.io/os": "linux"
            }
        },
        "versions": {
            "79.0": {
                "image": "selenoid/vnc:chrome_79.0"
            },
            "80.0": {
                "image": "selenoid/vnc:chrome_80.0"
            },
            "81.0": {
                "image": "selenoid/vnc:chrome_81.0"
            },
            "83.0": {
                "image": "selenoid/vnc:chrome_83.0"
            },
            "84.0": {
                "image": "selenoid/vnc:chrome_84.0"
            },
            "85.0": {
                "image": "selenoid/vnc:chrome_85.0"
            },
            "86.0": {
                "image": "selenoid/vnc:chrome_86.0"
            },
            "87.0": {
                "image": "selenoid/vnc:chrome_87.0"
            },
            "88.0": {
                "image": "selenoid/vnc:chrome_88.0"
            },
            "89.0": {
                "image": "selenoid/vnc:chrome_89.0"
            },
            "90.0": {
                "image": "selenoid/vnc:chrome_90.0"
            }
        }
    },
    "firefox": {
        "defaultVersion": "88.0",
        "path": "/wd/hub",
        "kernelCaps": ["SYS_ADMIN"],
        "versions": {
            "77.0": {
                "image": "selenoid/vnc:firefox_77.0"
            },
            "78.0": {
                "image": "selenoid/vnc:firefox_78.0"
            },
            "79.0": {
                "image": "selenoid/vnc:firefox_79.0"
            },
            "80.0": {
                "image": "selenoid/vnc:firefox_80.0"
            },
            "81.0": {
                "image": "selenoid/vnc:firefox_81.0"
            },
            "82.0": {
                "image": "selenoid/vnc:firefox_82.0"
            },
            "83.0": {
                "image": "selenoid/vnc:firefox_83.0"
            },
            "84.0": {
                "image": "selenoid/vnc:firefox_84.0"
            },
            "85.0": {
                "image": "selenoid/vnc:firefox_85.0"
            },
            "86.0": {
                "image": "selenoid/vnc:firefox_86.0"
            },
            "87.0": {
                "image": "selenoid/vnc:firefox_87.0"
            },
            "88.0": {
                "image": "selenoid/vnc:firefox_88.0"
            }
        }
    },
    "opera" : {
        "defaultVersion": "75.0",
        "path": "/",
        "kernelCaps": ["SYS_ADMIN"],
        "versions": {
            "65.0": {
                "image": "selenoid/vnc:opera_65.0"
            },
            "66.0": {
                "image": "selenoid/vnc:opera_66.0"
            },
            "67.0": {
                "image": "selenoid/vnc:opera_67.0"
            },
            "68.0": {
                "image": "selenoid/vnc:opera_68.0"
            },
            "69.0": {
                "image": "selenoid/vnc:opera_69.0"
            },
            "70.0": {
                "image": "selenoid/vnc:opera_70.0"
            },
            "71.0": {
                "image": "selenoid/vnc:opera_71.0"
            },
            "72.0": {
                "image": "selenoid/vnc:opera_72.0"
            },
            "73.0": {
                "image": "selenoid/vnc:opera_73.0"
            },
            "74.0": {
                "image": "selenoid/vnc:opera_74.0"
            },
            "75.0": {
                "image": "selenoid/vnc:opera_75.0"
            }
        }
    },
    "MicrosoftEdge" : {
        "defaultVersion": "91.0",
        "path": "/",
        "kernelCaps": ["SYS_ADMIN"],
        "versions": {
            "88.0": {
                "image": "browsers/edge:88.0"
            },
            "89.0": {
                "image": "browsers/edge:89.0"
            },
            "90.0": {
                "image": "browsers/edge:90.0"
            },
            "91.0": {
                "image": "browsers/edge:91.0"
            }
        }
    }
}
```
I've created a gist for the selenosis and seleniferous logs [here](https://gist.github.com/beerai/6bd2b90998364c94d1f378d45164cec6)

> Do you have any loadbalancer before selenosis? If so, any timeouts there?
Only the one defined in the selenosis service manifest from the selenosis-deploy repo. Azure creates an LB but the [docs ](https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-tcp-idle-timeout?tabs=tcp-reset-idle-portal)say the timeouts are 4 minutes


> How many non browser pods are running in selenosis namespace? please list them all coz deployment that you shared consists of 2 selenosis replicas with browser limit is 60, but log shows resource quota limit 81 :)

I was playing with the HPA at the time. The deployment had 2 replicas but it scales up to 60. The logs I've attached above had 61 pods running, 60 selenosis and 1 selenoid UI

**Comment by alcounit** [comment]
@beerai can you please also share DesiredCapabilities used to launch chrome 90

**Comment by beerai** [comment]
@alcounit sure, here they are:
```C#
            IWebDriver webDriver;
            options.AddArgument(@"--no-sandbox");
            options.AddArgument(@"--incognito");
            options.AddArgument(@"--start-maximized");
            options.AddArguments(@"--disable-infobars");
            options.AddUserProfilePreference("intl.accept_languages", "en-GB");
            options.AddArgument(@"--lang=en-GB");
            options.AddAdditionalCapability("enableVNC", true, true);
            options.AddUserProfilePreference("download.prompt_for_download", false);
            webDriver = new RemoteWebDriver(new Uri("http://10.240.0.10:4444/wd/hub"), options);

```

**Comment by alcounit** [comment]
I tried to run 10 sessions with 1 selenosis replica in AKS and have no problems, only added configmap for core-dns
```yaml corednsms.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  test.server: | # you may select any name here, but it must end with the .server file extension
    selenosis.svc.cluster.local:53 {
        errors
        kubernetes cluster.local {
          namespaces selenosis
        }
    }
```
![7LI8DMRJwi](https://user-images.githubusercontent.com/6169826/118038547-eb97b400-b377-11eb-9496-144ea358ff49.gif)

**Comment by beerai** [comment]
Could you try running with more sessions in parallel? I also have that configmap
![image](https://user-images.githubusercontent.com/2687469/118054331-6c32d080-b3c9-11eb-9b10-2967f330c8fd.png)
![image](https://user-images.githubusercontent.com/2687469/118054431-971d2480-b3c9-11eb-94cc-66b3391f0175.png)

Here's the manifest
```yaml
apiVersion: v1
data:
  selenosis.server: |
    selenosis.svc.cluster.local:53 {
        errors
        kubernetes cluster.local {
          namespaces selenosis
        }
    }
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system

```
