### ISSUE TITLE
Tests are failing with Session ID is required

### ISSUE THREAD

**Issue by madhank93** [alcounit/selenosis#48]
Hi @alcounit, Thank you creating and maintaining this project.

My tests are failing with Error: A sessionId is required for this command. 

Strange thing this when I specify HPA minReplica -2 or Selenosis replicas - 2. For first set of tests all the tests are failed and for the second time all the tests are getting passed.

My assumption is `--session-wait-timeout` and `--browser-wait-timeout` doesn't works.

`Selenosis.yml`

```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenosis
  namespace: selenosis
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: selenosis
  template:
    metadata:
      labels:
        app: selenosis
        selenosis.app.type: worker
      namespace: selenosis
    spec:
      containers:
        - args:
            [
              "/selenosis",
              "--browsers-config",
              "./config/browsers.yaml",
              "--namespace",
              "selenosis",
              "--service-name",
              "seleniferous",
              "--browser-limit",
              "20",
              "--proxy-image",
              "alcounit/seleniferous:v1.0.2",
              "--session-wait-timeout",
              "5m0s",
              "--browser-wait-timeout",
              "5m0s",
            ]
          image: alcounit/selenosis:v1.0.5
          name: selenosis
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "128Mi"
          ports:
            - containerPort: 4444
              name: selenium
              protocol: TCP
          volumeMounts:
            - mountPath: ./config
              name: browsers-config
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              path: /healthz
              port: 4444
            periodSeconds: 2
            initialDelaySeconds: 30
          livenessProbe:
            httpGet:
              path: /healthz
              port: 4444
            periodSeconds: 2
            initialDelaySeconds: 3
      volumes:
        - name: browsers-config
          configMap:
            name: selenosis-config
```
`e2e.yml`

```yml
apiVersion: batch/v1
kind: Job
metadata:
  name: e2e
  namespace: selenosis
spec:
  template:
    spec:
      containers:
        - name: e2e
          imagePullPolicy: IfNotPresent
          image: gcr.io/wdio-gke/e2e:latest
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "1Gi"
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      terminationGracePeriodSeconds: 0
```

`browser.yml`
```yml
chrome:
  defaultVersion: "91.0"
  path: "/"
  kernelCaps:
    - SYS_ADMIN
  versions:
    "91.0":
      image: "selenoid/chrome:91.0"
firefox:
  defaultVersion: "88.0"
  path: "/wd/hub"
  kernelCaps:
    - SYS_ADMIN
  versions:
    "88.0":
      image: "selenoid/firefox:88.0"
```

`wdio.conf.ts`
```ts
  hostname: "selenosis",
  port: 4444,
  path: "/wd/hub",
```

Full log - https://gist.github.com/f563647e56374e46101c5b27a29afc84
Error log - https://gist.github.com/madhank93/40b35660ca0db481a014c608e15f51a9
Application log - https://gist.github.com/cfc2edb65b362f1169b142e03629dcae
